name: DungeonInstances
version: 1.0.0
main: fr.eminiumgames.dungeonsinstances.DungeonInstances
api: '1.19'
api-version: '1.19'
description: Plugin pour gérer les instances de donjons dans Minecraft
authors:
  - fox3000foxy
commands:
  dungeon:
    description: Commande principale pour gérer les donjons et les groupes.
    usage: /dungeon <sous-commande>
permissions:
  dungeon.admin:
    description: Permission d'utiliser les commandes d'administration des donjons.
    default: op