name: DungeonInstances
version: 1.0.0
main: fr.eminiumgames.dungeonsinstances.DungeonInstances
api-version: 1.19
description: Plugin pour gérer les instances de donjons dans Minecraft
authors:
  - fox3000foxy
commands:
  dungeon:
    description: Commande principale pour gérer les donjons.
    usage: /dungeon <sous-commande>
  dparty:
    description: Commande pour gérer les groupes.
    usage: /dparty <sous-commande>