name: DungeonInstances
version: 1.0.0
main: fr.eminiumgames.dungeonsinstances.DungeonInstances
api: '1.19'
api-version: '1.19'
description: Plugin to manage dungeon instances in Minecraft
authors:
  - fox3000foxy
commands:
  dungeon:
    description: Main command for managing dungeons and parties.
    usage: /dungeon <sub-command> (e.g. /dungeon instance <name> [difficulty])
permissions:
  dungeon.admin:
    description: Permission to use dungeon administration commands.
    default: op